// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "totp-map.h"
#include "esp_log.h"
#include <time.h>

extern int setup_complete;
extern uint32_t LV_EVENT_SETUP_COMPLETE;

int calculate_new_bar_value(){
    struct tm *timeinfo; 
    time_t now;
    time(&now); 
    timeinfo = localtime(&now); 
    int val = 30 - timeinfo->tm_sec % 30; 
    return val;
}

void on_totp_component_label_value_changed(lv_event_t *e) {
    LV_LOG_INFO("on_totp_component_label_value_changed");
    lv_obj_t *label = lv_event_get_target(e);
    TotpValueChangeEvent * data = (TotpValueChangeEvent *)lv_event_get_param(e);
    char *totp = get_totp_by_index(data->index);
    if(totp){
        // NOTE: we copy the value to the label instead of using its reference because the mem address where the totp pointer points to could be dealocated
        lv_label_set_text(label, strdup(totp));
    }
}

void on_totp_component_bar_value_changed(lv_event_t *e){
    LV_LOG_INFO("on_totp_component_bar_value_changed");
    lv_obj_t *bar = lv_event_get_target(e);
    int val = calculate_new_bar_value();
    lv_bar_set_value(bar, val, LV_ANIM_OFF);
}
