// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_TotpScreen_screen_init(void)
{
ui_TotpScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_TotpScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TotpScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TotpScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_TotpScreen);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, -20 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"TOTP");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x090000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar2 = lv_bar_create(ui_TotpScreen);
lv_bar_set_range(ui_Bar2, 0,30);
lv_bar_set_value(ui_Bar2,30,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, 150);
lv_obj_set_height( ui_Bar2, 10);
lv_obj_set_x( ui_Bar2, 0 );
lv_obj_set_y( ui_Bar2, 30 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Label2, ui_event_Label2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Bar2, ui_event_Bar2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TotpScreen, ui_event_TotpScreen, LV_EVENT_ALL, NULL);

}
