// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"
#include "constants.h"

void ui_touch_calibration_screen_init(void)
{
    ui_touch_calibration_screen = lv_obj_create(NULL);
    lv_obj_set_user_data(ui_touch_calibration_screen, (void *)TOUCH_CALIBRATION_SCREEN_NAME);
    lv_obj_set_style_bg_color(ui_touch_calibration_screen, lv_color_make(0, 0, 0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_touch_calibration_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_flex_flow(ui_touch_calibration_screen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_touch_calibration_screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_layout(ui_touch_calibration_screen, LV_LAYOUT_FLEX);
}

void display_first_calibration_point()
{
    circle1 = lv_obj_create(ui_touch_calibration_screen);
    lv_obj_set_size(circle1, 50, 50);
    lv_obj_set_style_radius(circle1, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(circle1, lv_color_make(255, 0, 0), LV_PART_MAIN);
    lv_obj_align(circle1, LV_ALIGN_TOP_LEFT, 20, 20); // Position in the top-left corner

    // Add a label with the number 1
    lv_obj_t *label = lv_label_create(circle1);
    lv_label_set_text(label, "1");
    lv_obj_center(label);
}

void change_first_calibration_point_green()
{
    lv_obj_set_style_bg_color(circle1, lv_color_make(0, 255, 0), LV_PART_MAIN);
}

void display_second_calibration_point()
{
    circle2 = lv_obj_create(ui_touch_calibration_screen);
    lv_obj_set_size(circle2, 50, 50);
    lv_obj_set_style_radius(circle2, LV_RADIUS_CIRCLE, 0);
    lv_obj_set_style_bg_color(circle2, lv_color_make(255, 0, 0), LV_PART_MAIN);
    lv_obj_align(circle2, LV_ALIGN_BOTTOM_RIGHT, -20, -20); // Position in the bottom-right corner

    // Add a label with the number 2
    lv_obj_t *label = lv_label_create(circle2);
    lv_label_set_text(label, "2");
    lv_obj_center(label);
}

void change_second_calibration_point_green()
{
    lv_obj_set_style_bg_color(circle2, lv_color_make(0, 255, 0), LV_PART_MAIN);
}

void display_success_message()
{
    success_label = lv_label_create(ui_touch_calibration_screen);
    lv_label_set_text(success_label, "Touch configured");
    lv_obj_set_style_text_color(success_label, lv_color_make(255, 255, 255), LV_PART_MAIN);
    lv_obj_align(success_label, LV_ALIGN_CENTER, 0, 0);
}